function expr = DataSteadyPolyScalarKappaNeumannSource(x1,x2,n1,n2)
%DATASTEADYPOLYSCALARKAPPANEUMANNSOURCE
%    EXPR = DATASTEADYPOLYSCALARKAPPANEUMANNSOURCE(X1,X2,N1,N2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    06-Aug-2016 01:09:44

expr = n1.*(x1.*2.0+x2.*3.0+2.0)+n2.*(x1.*3.0-x2.*4.0+3.0);
