function expr = DataUnsteadyPolyExactSolution(t,x1,x2)
%DATAUNSTEADYPOLYEXACTSOLUTION
%    EXPR = DATAUNSTEADYPOLYEXACTSOLUTION(T,X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    06-Aug-2016 22:00:28

expr = x1.*2.0+x2.*3.0+cos(t)+x1.*x2+x1.^2+x2.^2;
