function expr = DataSteadyPolyScalarKappaDomainSource(x1,x2)
%DATASTEADYPOLYSCALARKAPPADOMAINSOURCE
%    EXPR = DATASTEADYPOLYSCALARKAPPADOMAINSOURCE(X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    06-Aug-2016 01:09:44

expr = x1.*4.0+x2.*6.0+x1.*x2.*6.0+x1.^2.*2.0-x2.^2.*4.0+3.0;
