function expr = DataUnsteadyPolyZeroExactSolution(t,x1,x2)
%DATAUNSTEADYPOLYZEROEXACTSOLUTION
%    EXPR = DATAUNSTEADYPOLYZEROEXACTSOLUTION(T,X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    29-Jul-2016 13:56:10

expr = x1.*x2.*cos(t).*(x1-3.0).*(x2-3.0);
