function expr = DataSteadyPolyDomainSource(x1,x2)
%DATASTEADYPOLYDOMAINSOURCE
%    EXPR = DATASTEADYPOLYDOMAINSOURCE(X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    10-Aug-2016 23:06:59

expr = x1.*4.0+x2.*6.0+x1.*x2.*6.0+x1.^2.*2.0-x2.^2.*4.0+3.0;
