function expr = DataUnsteadyPolyDomainSource(t,x1,x2)
%DATAUNSTEADYPOLYDOMAINSOURCE
%    EXPR = DATAUNSTEADYPOLYDOMAINSOURCE(T,X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    06-Aug-2016 22:00:28

expr = sin(t)+2.8e1;
